name: Trustpilot Playwright Scraper

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install OS dependencies for Playwright
        run: |
          set -e
          echo "Running apt-get update..."
          sudo apt-get update -y
          echo "Installing required packages..."
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
            libxcomposite1 libxrandr2 libgbm1 libgtk-3-0 libxdamage1 libxfixes3 \
            libpangocairo-1.0-0 libpango-1.0-0 libasound2t64

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: python trustpilot_playwright_scraper.py

      - name: Commit and push updated Excel
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.xlsx
          git diff --cached --quiet || git commit -m "Update Trustpilot reviews"
          git push
