      - name: Install OS dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
            libxcomposite1 libxrandr2 libgbm1 libgtk-3-0 libxdamage1 libxfixes3 \
            libpangocairo-1.0-0 libpango-1.0-0 libasound2
